version: '3'
services: 
    db:
        image: 'postgres:11.8'
        container_name: 'db-nest-pg'
        ports: 
            - 5433:5432
        nvironment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgress
            - POSTGRES_DB=nest