version: '3'
services: 
    db:
        image: 'postgres:11.8'
        container_name: 'db-nest-pg'
        ports: 
            - 5433:5432
        environment:
            - POSTGRES_USER=nest
            - POSTGRES_PASSWORD=nest
            - POSTGRES_DB=nest