version: '3'
services: 
    db-mongo:
        image: 'mongo:4.0.20-xenial'
        container_name: 'mongo-nest-try'
        ports: 
            - 27017:27017
        environment: 
            - MONGO_INITDB_DATABASE=nest
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret